version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: user-local
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user-local -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  flyway:
    image: flyway/flyway:latest
    container_name: flyway_migrations
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./db/migrations:/flyway/sql
    command:
      - -url=jdbc:postgresql://db:5432/mydb
      - -user=user-local
      - -password=password
      - -schemas=demo
      - -placeholders.schema=demo
      - -connectRetries=60
      - -baselineOnMigrate=true
      - migrate

  app:
    build: .
    container_name: stock_loading_app
    ports:
      - "3000:3000"
    depends_on:
      flyway:
        condition: service_completed_successfully
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_USER: user-local
      DB_PASSWORD: password
      DB_NAME: mydb
      DB_PORT: 5432
    restart: unless-stopped

volumes:
  db_data: